/* 
    TO DO LIST :
        - ATTAQUER L'ONGLET HOTEL :
            - 1 - VERIFIER SI ON NE PAS METTRE PLUS D'OPTION DONE
            - 2 - REARRANGER L'INTERFACE DONE
            - 3 - FAIRE LES JOINTURES POUR RECUPERER LA LISTE DES HOTELS DONE
 */
package com.hotelApp;

import java.awt.event.ItemEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * @author Karl La Grassa
 */
public class IHM_Principale extends javax.swing.JFrame {

    /**
     * Creates new form IHM_Principale
     */
    /* ATTRIBUTS */
    String url;
    String user;
    String password;
    int nbTarifs;
    char tarifs[];
    C_BDD BDD;

    /* Hôtel commun et chambre commune, modifiés selon que l'utilisateur 
    est en mode création ou modification */
    C_Hotel Hotel;
    C_Chambre Chambre;

    /* flagCreationHotel true si l'on doit ajouter un hotel
                        false si l'on est en train de modifier
     */
    Boolean flagHotel, flagCreationHotel, flagCreationChambre;

    JRadioButton RadioBoutonSdB[];
    JRadioButton RadioBoutonWC[];

    public IHM_Principale() {
        initComponents();

        url = "jdbc:mysql://localhost:3306/hotel";
        user = "root";
        password = "";

        BDD = new C_BDD(url, user, password);
        flagHotel = true;
        flagCreationHotel = false;
        flagCreationChambre = false;

        /* Initialisation des tableaux de radio bouton */
        RadioBoutonSdB = new JRadioButton[2];
        RadioBoutonWC = new JRadioButton[2];

        RadioBoutonSdB[0] = radSdBOui;
        RadioBoutonSdB[1] = radSdBNon;

        RadioBoutonWC[0] = radWCOui;
        RadioBoutonWC[1] = radWCNon;

        /* Cacher les panels pour les gestion hôtels et chambres (ergonomie) */
        OngletHotelAjouter.setVisible(false);
        OngletChambreAjouter.setVisible(false);

        /* Chargement de toutes les combo box */
        if (BDD.Connecter() == 0) {
            /* Combo box Hotels */
            MettreAJourComboBox(comboHotel, "hotel", BDD);
            MettreAJourComboBox(comboHotelChambre, "hotel", BDD);
            MettreAJourComboBox(comboHotelBilans, "hotel", BDD);
            MettreAJourComboBox(comboChambre, "chambre", BDD);

            /* Combo box chambres */
        } /* Combo box chambres */ else {
            JOptionPane.showMessageDialog(rootPane, BDD.getErrno(),
                    "Erreur SQL", JOptionPane.ERROR_MESSAGE);
        }

        RemplirBoxTarifs(6);

    } // Fin IHM_Principale

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OngletCodePerdu = new javax.swing.JPanel();
        OngletModifHotel = new javax.swing.JScrollPane();
        GestionnaireOnglet = new javax.swing.JTabbedPane();
        OngletHotel = new javax.swing.JPanel();
        btnAjouterHotel = new javax.swing.JButton();
        btnModifierHotel = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btnSupprimerHotel = new javax.swing.JButton();
        comboHotel = new javax.swing.JComboBox<>();
        lblChangerHotel = new javax.swing.JLabel();
        OngletHotelAjouter = new javax.swing.JPanel();
        btnValiderHotel = new javax.swing.JButton();
        btnAnnulerHotel = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listesServices = new javax.swing.JTextArea();
        comboServices = new javax.swing.JComboBox<>();
        btnAjouterServices = new javax.swing.JButton();
        lblListeServices = new javax.swing.JLabel();
        txtNomHotel = new javax.swing.JTextField();
        txtNumFixe = new javax.swing.JTextField();
        txtAdresse = new javax.swing.JTextField();
        txtCodePostal = new javax.swing.JTextField();
        txtVille = new javax.swing.JTextField();
        lblVille = new javax.swing.JLabel();
        lblCP = new javax.swing.JLabel();
        lblAdresse = new javax.swing.JLabel();
        lblNumeroFixe = new javax.swing.JLabel();
        lblNomHotel = new javax.swing.JLabel();
        lblStatusHotel = new javax.swing.JLabel();
        OngletChambres = new javax.swing.JPanel();
        lblHotelChambres = new javax.swing.JLabel();
        btnSupprimerChambre = new javax.swing.JButton();
        btnModifierChambre = new javax.swing.JButton();
        btnAjouterChambre = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        comboHotelChambre = new javax.swing.JComboBox<>();
        comboChambre = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();
        OngletChambreAjouter = new javax.swing.JPanel();
        btnAnnulerChambre = new javax.swing.JButton();
        btnValiderChambre = new javax.swing.JButton();
        txtLitsSimples = new javax.swing.JTextField();
        lblLitsSimples = new javax.swing.JLabel();
        lblLitsDoubles = new javax.swing.JLabel();
        txtLitsDoubles = new javax.swing.JTextField();
        lblCouchages = new javax.swing.JLabel();
        txtNumChambre = new javax.swing.JTextField();
        lblNumChambre = new javax.swing.JLabel();
        lblTarif = new javax.swing.JLabel();
        boxTarifs = new javax.swing.JComboBox<>();
        lblSalleDeBains = new javax.swing.JLabel();
        radSdBOui = new javax.swing.JRadioButton();
        radWCOui = new javax.swing.JRadioButton();
        lblWC = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtAddrMac = new javax.swing.JTextField();
        radWCNon = new javax.swing.JRadioButton();
        radSdBNon = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        lblNbCouchages = new javax.swing.JLabel();
        OngletReception = new javax.swing.JPanel();
        lblNumReservation = new javax.swing.JLabel();
        txtNumeroReservation = new javax.swing.JTextField();
        sepReceptionClient = new javax.swing.JSeparator();
        btnOkReservation = new javax.swing.JButton();
        lblNomReservation = new javax.swing.JLabel();
        lblPrenomReservation = new javax.swing.JLabel();
        lblDateArrivee = new javax.swing.JLabel();
        lblDateFin = new javax.swing.JLabel();
        btnPaiementRecu = new javax.swing.JButton();
        btnCodeChambre = new javax.swing.JButton();
        txtNomReservation = new javax.swing.JTextField();
        txtPrenomReservation = new javax.swing.JTextField();
        txtDateArrivee = new javax.swing.JTextField();
        txtDateFin = new javax.swing.JTextField();
        lblNbrPersonnes = new javax.swing.JLabel();
        lblChambresReservees = new javax.swing.JLabel();
        lblPrixRestant = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        OngletBilans = new javax.swing.JPanel();
        lblBilans = new javax.swing.JLabel();
        comboPeriodeBilan = new javax.swing.JComboBox<>();
        comboTypeGraphique = new javax.swing.JComboBox<>();
        lblPeriodeBilan = new javax.swing.JLabel();
        lblTypeGraphique = new javax.swing.JLabel();
        panelGraphiqueBilans = new javax.swing.JPanel();
        btnGenererBilans = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        comboHotelBilans = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout OngletCodePerduLayout = new javax.swing.GroupLayout(OngletCodePerdu);
        OngletCodePerdu.setLayout(OngletCodePerduLayout);
        OngletCodePerduLayout.setHorizontalGroup(
            OngletCodePerduLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 428, Short.MAX_VALUE)
        );
        OngletCodePerduLayout.setVerticalGroup(
            OngletCodePerduLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 423, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAjouterHotel.setText("Nouvel Hôtel");
        btnAjouterHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterHotelActionPerformed(evt);
            }
        });

        btnModifierHotel.setText("Modifier");
        btnModifierHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierHotelActionPerformed(evt);
            }
        });

        btnSupprimerHotel.setText("Supprimer");
        btnSupprimerHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerHotelActionPerformed(evt);
            }
        });

        comboHotel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboHotel.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboHotelItemStateChanged(evt);
            }
        });
        comboHotel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboHotelMouseClicked(evt);
            }
        });

        lblChangerHotel.setText("Choisir hôtel");

        btnValiderHotel.setText("Valider");
        btnValiderHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValiderHotelActionPerformed(evt);
            }
        });

        btnAnnulerHotel.setText("Annuler");
        btnAnnulerHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnulerHotelActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        listesServices.setColumns(20);
        listesServices.setRows(5);
        jScrollPane1.setViewportView(listesServices);

        comboServices.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAjouterServices.setText("Ajouter");

        lblListeServices.setText("Liste des services");

        lblVille.setText("Ville");

        lblCP.setText("Code Postal");

        lblAdresse.setText("Adresse");

        lblNumeroFixe.setText("Numéro Fixe");

        lblNomHotel.setText("Hôtel");

        lblStatusHotel.setText("jLabel5");

        javax.swing.GroupLayout OngletHotelAjouterLayout = new javax.swing.GroupLayout(OngletHotelAjouter);
        OngletHotelAjouter.setLayout(OngletHotelAjouterLayout);
        OngletHotelAjouterLayout.setHorizontalGroup(
            OngletHotelAjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OngletHotelAjouterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnValiderHotel)
                .addGap(18, 18, 18)
                .addComponent(btnAnnulerHotel)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(311, 311, 311))
            .addGroup(OngletHotelAjouterLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(OngletHotelAjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OngletHotelAjouterLayout.createSequentialGroup()
                        .addComponent(lblStatusHotel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(OngletHotelAjouterLayout.createSequentialGroup()
                        .addGroup(OngletHotelAjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(OngletHotelAjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblAdresse)
                                .addComponent(txtAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(OngletHotelAjouterLayout.createSequentialGroup()
                                    .addComponent(lblNomHotel)
                                    .addGap(51, 51, 51)
                                    .addComponent(txtNomHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(OngletHotelAjouterLayout.createSequentialGroup()
                                    .addComponent(lblNumeroFixe)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNumFixe, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(OngletHotelAjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(OngletHotelAjouterLayout.createSequentialGroup()
                                    .addComponent(lblCP)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCodePostal, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(OngletHotelAjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblVille)
                                    .addComponent(txtVille, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 307, Short.MAX_VALUE)
                        .addGroup(OngletHotelAjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblListeServices)
                            .addGroup(OngletHotelAjouterLayout.createSequentialGroup()
                                .addComponent(comboServices, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAjouterServices))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(247, 247, 247))))
        );
        OngletHotelAjouterLayout.setVerticalGroup(
            OngletHotelAjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OngletHotelAjouterLayout.createSequentialGroup()
                .addComponent(lblStatusHotel)
                .addGap(14, 14, 14)
                .addGroup(OngletHotelAjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(OngletHotelAjouterLayout.createSequentialGroup()
                        .addComponent(lblListeServices)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(OngletHotelAjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboServices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAjouterServices))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(OngletHotelAjouterLayout.createSequentialGroup()
                        .addGroup(OngletHotelAjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(OngletHotelAjouterLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(lblNomHotel)
                                .addGap(33, 33, 33)
                                .addGroup(OngletHotelAjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblNumeroFixe)
                                    .addComponent(txtNumFixe, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(lblAdresse)
                                .addGap(6, 6, 6)
                                .addComponent(txtAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNomHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(OngletHotelAjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodePostal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblVille)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtVille, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addGroup(OngletHotelAjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnValiderHotel)
                    .addComponent(btnAnnulerHotel)
                    .addComponent(jButton1))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout OngletHotelLayout = new javax.swing.GroupLayout(OngletHotel);
        OngletHotel.setLayout(OngletHotelLayout);
        OngletHotelLayout.setHorizontalGroup(
            OngletHotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OngletHotelLayout.createSequentialGroup()
                .addGroup(OngletHotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OngletHotelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(OngletHotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addGroup(OngletHotelLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(lblChangerHotel)
                                .addGap(18, 18, 18)
                                .addComponent(comboHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btnModifierHotel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSupprimerHotel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAjouterHotel)
                                .addGap(102, 102, 102))))
                    .addComponent(OngletHotelAjouter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        OngletHotelLayout.setVerticalGroup(
            OngletHotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OngletHotelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(OngletHotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSupprimerHotel)
                    .addComponent(lblChangerHotel)
                    .addComponent(btnAjouterHotel)
                    .addComponent(btnModifierHotel))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(OngletHotelAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );

        GestionnaireOnglet.addTab("Gestion Hôtel", OngletHotel);

        lblHotelChambres.setText("Choisir hôtel");

        btnSupprimerChambre.setText("Supprimer");
        btnSupprimerChambre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerChambreActionPerformed(evt);
            }
        });

        btnModifierChambre.setText("Modifier");
        btnModifierChambre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierChambreActionPerformed(evt);
            }
        });

        btnAjouterChambre.setText("Nouvelle chambre");
        btnAjouterChambre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterChambreActionPerformed(evt);
            }
        });

        jLabel2.setText("Choisir chambre");

        comboHotelChambre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboHotelChambre.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboHotelChambreItemStateChanged(evt);
            }
        });
        comboHotelChambre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                comboHotelChambreMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboHotelChambreMouseClicked(evt);
            }
        });

        comboChambre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboChambre.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboChambreItemStateChanged(evt);
            }
        });
        comboChambre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboChambreMouseClicked(evt);
            }
        });
        comboChambre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboChambreActionPerformed(evt);
            }
        });

        btnAnnulerChambre.setText("Annuler");

        btnValiderChambre.setText("Valider");
        btnValiderChambre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValiderChambreActionPerformed(evt);
            }
        });

        txtLitsSimples.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLitsSimplesActionPerformed(evt);
            }
        });

        lblLitsSimples.setText("Lits simples");

        lblLitsDoubles.setText("Lits doubles");

        lblCouchages.setText("Couchages");

        lblNumChambre.setText("Numéro chambre");

        lblTarif.setText("Tarif");

        boxTarifs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblSalleDeBains.setText("Salle de bains ?");

        radSdBOui.setText("Oui");
        radSdBOui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radSdBOuiActionPerformed(evt);
            }
        });

        radWCOui.setText("Oui");
        radWCOui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radWCOuiActionPerformed(evt);
            }
        });

        lblWC.setText("WC ?");

        jLabel3.setText("Adresse Mac de la poignée");

        radWCNon.setText("Non");
        radWCNon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radWCNonActionPerformed(evt);
            }
        });

        radSdBNon.setText("Non");
        radSdBNon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radSdBNonActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lblNbCouchages.setText("jLabel1");

        javax.swing.GroupLayout OngletChambreAjouterLayout = new javax.swing.GroupLayout(OngletChambreAjouter);
        OngletChambreAjouter.setLayout(OngletChambreAjouterLayout);
        OngletChambreAjouterLayout.setHorizontalGroup(
            OngletChambreAjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OngletChambreAjouterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OngletChambreAjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OngletChambreAjouterLayout.createSequentialGroup()
                        .addComponent(lblTarif)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(boxTarifs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(OngletChambreAjouterLayout.createSequentialGroup()
                        .addGroup(OngletChambreAjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(OngletChambreAjouterLayout.createSequentialGroup()
                                .addComponent(lblLitsSimples)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtLitsSimples, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(OngletChambreAjouterLayout.createSequentialGroup()
                                .addGroup(OngletChambreAjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblLitsDoubles)
                                    .addComponent(lblNumChambre))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(OngletChambreAjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNumChambre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLitsDoubles, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(OngletChambreAjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(OngletChambreAjouterLayout.createSequentialGroup()
                                .addGap(172, 172, 172)
                                .addGroup(OngletChambreAjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSalleDeBains, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblWC, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(OngletChambreAjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radSdBOui)
                                    .addComponent(radWCOui))
                                .addGap(29, 29, 29)
                                .addGroup(OngletChambreAjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radSdBNon)
                                    .addComponent(radWCNon)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OngletChambreAjouterLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAddrMac, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OngletChambreAjouterLayout.createSequentialGroup()
                        .addComponent(lblCouchages)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNbCouchages)
                        .addGap(359, 359, 359)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(OngletChambreAjouterLayout.createSequentialGroup()
                .addGap(307, 307, 307)
                .addComponent(btnValiderChambre)
                .addGap(18, 18, 18)
                .addComponent(btnAnnulerChambre)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(0, 254, Short.MAX_VALUE))
        );
        OngletChambreAjouterLayout.setVerticalGroup(
            OngletChambreAjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OngletChambreAjouterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OngletChambreAjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxTarifs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTarif))
                .addGap(26, 26, 26)
                .addGroup(OngletChambreAjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(OngletChambreAjouterLayout.createSequentialGroup()
                        .addGroup(OngletChambreAjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNumChambre)
                            .addComponent(txtNumChambre, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(OngletChambreAjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLitsDoubles)
                            .addComponent(txtLitsDoubles, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6))
                    .addGroup(OngletChambreAjouterLayout.createSequentialGroup()
                        .addGroup(OngletChambreAjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radSdBOui)
                            .addComponent(lblSalleDeBains))
                        .addGap(31, 31, 31)
                        .addGroup(OngletChambreAjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblWC)
                            .addComponent(radWCOui)))
                    .addGroup(OngletChambreAjouterLayout.createSequentialGroup()
                        .addComponent(radSdBNon)
                        .addGap(31, 31, 31)
                        .addComponent(radWCNon)))
                .addGap(18, 18, 18)
                .addGroup(OngletChambreAjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAddrMac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLitsSimples, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLitsSimples))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(OngletChambreAjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCouchages)
                    .addComponent(lblNbCouchages))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(OngletChambreAjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnValiderChambre)
                    .addComponent(btnAnnulerChambre)
                    .addComponent(jButton2))
                .addGap(147, 147, 147))
        );

        javax.swing.GroupLayout OngletChambresLayout = new javax.swing.GroupLayout(OngletChambres);
        OngletChambres.setLayout(OngletChambresLayout);
        OngletChambresLayout.setHorizontalGroup(
            OngletChambresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OngletChambresLayout.createSequentialGroup()
                .addGroup(OngletChambresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OngletChambresLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator3))
                    .addGroup(OngletChambresLayout.createSequentialGroup()
                        .addGroup(OngletChambresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(OngletChambresLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(lblHotelChambres)
                                .addGap(21, 21, 21)
                                .addComponent(comboHotelChambre, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboChambre, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnModifierChambre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSupprimerChambre)
                                .addGap(94, 94, 94)
                                .addComponent(btnAjouterChambre))
                            .addGroup(OngletChambresLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(OngletChambreAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 260, Short.MAX_VALUE)))
                .addContainerGap())
        );
        OngletChambresLayout.setVerticalGroup(
            OngletChambresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OngletChambresLayout.createSequentialGroup()
                .addGroup(OngletChambresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OngletChambresLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(OngletChambresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHotelChambres)
                            .addComponent(comboHotelChambre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OngletChambresLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(OngletChambresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(comboChambre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModifierChambre)
                            .addComponent(btnAjouterChambre)
                            .addComponent(btnSupprimerChambre))))
                .addGap(19, 19, 19)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OngletChambreAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        GestionnaireOnglet.addTab("Gestion chambres", OngletChambres);

        OngletReception.setEnabled(false);

        lblNumReservation.setText("N° Réservation");

        btnOkReservation.setText("OK");

        lblNomReservation.setText("Nom");

        lblPrenomReservation.setText("Prénom");

        lblDateArrivee.setText("Date arrivée");

        lblDateFin.setText("Date fin");

        btnPaiementRecu.setText("Valider paiement");
        btnPaiementRecu.setEnabled(false);

        btnCodeChambre.setText("Code Chambre");
        btnCodeChambre.setEnabled(false);

        lblNbrPersonnes.setText("Nombre de personnes");

        lblChambresReservees.setText("Chambres réservée(s)");

        lblPrixRestant.setText("Prix restant à payer");

        javax.swing.GroupLayout OngletReceptionLayout = new javax.swing.GroupLayout(OngletReception);
        OngletReception.setLayout(OngletReceptionLayout);
        OngletReceptionLayout.setHorizontalGroup(
            OngletReceptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OngletReceptionLayout.createSequentialGroup()
                .addGroup(OngletReceptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OngletReceptionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(sepReceptionClient))
                    .addGroup(OngletReceptionLayout.createSequentialGroup()
                        .addGroup(OngletReceptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(OngletReceptionLayout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(lblNumReservation)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNumeroReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnOkReservation))
                            .addGroup(OngletReceptionLayout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addGroup(OngletReceptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNomReservation)
                                    .addComponent(lblPrenomReservation)
                                    .addComponent(lblDateArrivee)
                                    .addComponent(lblDateFin)
                                    .addComponent(lblNbrPersonnes)
                                    .addComponent(lblChambresReservees)
                                    .addComponent(lblPrixRestant))
                                .addGap(47, 47, 47)
                                .addGroup(OngletReceptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNomReservation)
                                    .addComponent(txtPrenomReservation)
                                    .addComponent(txtDateArrivee)
                                    .addComponent(txtDateFin)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField1)
                                    .addComponent(jTextField2)))
                            .addGroup(OngletReceptionLayout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addComponent(btnPaiementRecu)
                                .addGap(36, 36, 36)
                                .addComponent(btnCodeChambre)))
                        .addGap(0, 568, Short.MAX_VALUE)))
                .addContainerGap())
        );
        OngletReceptionLayout.setVerticalGroup(
            OngletReceptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OngletReceptionLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(OngletReceptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumReservation)
                    .addComponent(txtNumeroReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOkReservation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sepReceptionClient, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(OngletReceptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNomReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomReservation))
                .addGap(18, 18, 18)
                .addGroup(OngletReceptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrenomReservation)
                    .addComponent(txtPrenomReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(OngletReceptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDateArrivee)
                    .addComponent(txtDateArrivee, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(OngletReceptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDateFin)
                    .addComponent(txtDateFin, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(OngletReceptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNbrPersonnes)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(OngletReceptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(lblChambresReservees))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(OngletReceptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrixRestant))
                .addGap(18, 132, Short.MAX_VALUE)
                .addGroup(OngletReceptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPaiementRecu)
                    .addComponent(btnCodeChambre))
                .addGap(71, 71, 71))
        );

        GestionnaireOnglet.addTab("Reception client", OngletReception);

        lblBilans.setText("Bilans");

        comboPeriodeBilan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboTypeGraphique.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblPeriodeBilan.setText("Période du bilan :");

        lblTypeGraphique.setText("Type de graphique :");

        javax.swing.GroupLayout panelGraphiqueBilansLayout = new javax.swing.GroupLayout(panelGraphiqueBilans);
        panelGraphiqueBilans.setLayout(panelGraphiqueBilansLayout);
        panelGraphiqueBilansLayout.setHorizontalGroup(
            panelGraphiqueBilansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        panelGraphiqueBilansLayout.setVerticalGroup(
            panelGraphiqueBilansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 356, Short.MAX_VALUE)
        );

        btnGenererBilans.setText("Générer");

        jLabel4.setText("Choisir hotel");

        comboHotelBilans.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout OngletBilansLayout = new javax.swing.GroupLayout(OngletBilans);
        OngletBilans.setLayout(OngletBilansLayout);
        OngletBilansLayout.setHorizontalGroup(
            OngletBilansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OngletBilansLayout.createSequentialGroup()
                .addGroup(OngletBilansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OngletBilansLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(OngletBilansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTypeGraphique)
                            .addComponent(lblPeriodeBilan)
                            .addComponent(lblBilans)
                            .addComponent(comboPeriodeBilan, 0, 183, Short.MAX_VALUE)
                            .addComponent(comboTypeGraphique, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addComponent(comboHotelBilans, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(OngletBilansLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(btnGenererBilans)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 370, Short.MAX_VALUE)
                .addComponent(panelGraphiqueBilans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
        );
        OngletBilansLayout.setVerticalGroup(
            OngletBilansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OngletBilansLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(OngletBilansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelGraphiqueBilans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(OngletBilansLayout.createSequentialGroup()
                        .addComponent(lblBilans)
                        .addGap(41, 41, 41)
                        .addComponent(lblPeriodeBilan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboPeriodeBilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(lblTypeGraphique)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboTypeGraphique, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboHotelBilans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(btnGenererBilans)))
                .addContainerGap(222, Short.MAX_VALUE))
        );

        GestionnaireOnglet.addTab("Editer bilans", OngletBilans);

        OngletModifHotel.setViewportView(GestionnaireOnglet);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OngletModifHotel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1043, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(OngletModifHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Met a jour les combo box avec les listes d'hôtels où de chambres selon ce
     * que demande l'utilisateu
     *
     * @param comboBox ComboBox à mettre à jour
     * @param type Chambre ou Hotel
     * @param BDD Handler MYSQL
     */
    public void MettreAJourComboBox(JComboBox comboBox, String type, C_BDD BDD) {
        comboBox.removeAllItems();
        if (type.equals("hotel")) {
            try {
                Statement statement = BDD.getConnection().createStatement();
                String requete = "SELECT `nom` FROM `t_hotel` WHERE 1";
                ResultSet resultat = statement.executeQuery(requete);

                while (resultat.next()) {
                    comboBox.addItem(resultat.getString(1));
                }
            } catch (SQLException ex) {
                Logger.getLogger(IHM_Principale.class.getName())
                        .log(Level.SEVERE, null, ex);
            }
        }
        if (type.equals("chambre")) {
            /* Récupération chambres */
            String hotelSelectionne = comboHotelChambre.getSelectedItem().toString();
            try {
                Statement statement = BDD.getConnection().createStatement();
                String requete = "SELECT c.numero"
                        + " FROM t_chambre c"
                        + " INNER JOIN t_hotel h"
                        + " ON h.id_hotel = c.id_hotel"
                        + " WHERE h.nom = '" + hotelSelectionne + "'";
                ResultSet resultat = statement.executeQuery(requete);

                while (resultat.next()) {
                    comboBox.addItem(resultat.getString(1));
                }
            } catch (SQLException ex) {
                Logger.getLogger(IHM_Principale.class.getName())
                        .log(Level.SEVERE, null, ex);
            }
        }
    }

    /**
     * Remplit la box code tarif dans l'onglet chambre
     *
     * @param handler - Handler MySQL
     */
    private void RemplirBoxTarifs(int nbTarifs) {
        /* Initialisation liste tarifs */
        tarifs = new char[nbTarifs];
        boxTarifs.removeAllItems();
        for (int i = 0; i < nbTarifs; i++) {
            /* 65 représente la lettre A en ASCII */
            tarifs[i] = (char) (65 + i);
            boxTarifs.addItem(Character.toString(tarifs[i]));
        }
    }

    /**
     * Change un 'set' de radio bouton
     *
     * @param tableau le groupement de radio bouton, soit RadioBoutonSdB[]
     * RadioBoutonWC[]
     * @param position le bouton Oui ou Non (respectivement 0 et 1)
     * @param etat activé ou pas (true ou false)
     */
    private void ChangerEtatRadBouton(JRadioButton[] tableau, int position,
            boolean etat) {
        for (int i = 0; i < tableau.length; i++) {
            tableau[i].setSelected(false);
        }
        if (position >= 0 && position <= tableau.length) {
            tableau[position].setSelected(etat);
        }
    }

    /**
     * Change un 'set de radio bouton en prenant en compte le paramètre état, Le
     * changement se fait automatiquement (contrairement a l'autre méthode qui
     * demande la position du bouton à changer)
     *
     * @param tableau qui contient les radio boutons
     * @param etat à prendre
     */
    private void ChangerEtatRadBouton(JRadioButton[] tableau, boolean etat) {
        if (etat) {
            ChangerEtatRadBouton(tableau, 0, true);
        } else {
            ChangerEtatRadBouton(tableau, 1, true);
        }
    }

    /**
     * Rempli tous les champs de l'onglet Chambre avec les informations sur la
     * chambre demandée
     *
     * @param chambre chambre demandée
     */
    private void RemplirInfoChambre(int numeroChambre, C_BDD handler) {
        Chambre = new C_Chambre(numeroChambre, BDD);
        boxTarifs.addItem(Character.toString(Chambre.GetCodeTarif()));
        txtNumChambre.setText(Integer.toString(Chambre.GetNumero()));
        lblNbCouchages.setText(Integer.toString(Chambre.GetNbLitDouble()
                + Chambre.GetNbLitSimple()));
        txtLitsDoubles.setText(Integer.toString(Chambre.GetNbLitDouble()));
        txtLitsSimples.setText(Integer.toString(Chambre.GetNbLitSimple()));
        txtAddrMac.setText(Chambre.GetAddrMac());
        ChangerEtatRadBouton(RadioBoutonSdB, Chambre.aUneSdB());
        ChangerEtatRadBouton(RadioBoutonWC, Chambre.aUnWC());
    }

    /**
     * Vide les champs de l'onglet 'Gestion Hotel'
     */
    private void ViderChampsHotel() {
        txtNomHotel.setText("");
        txtNumFixe.setText("");
        txtAdresse.setText("");
        txtCodePostal.setText("");
        txtVille.setText("");
        listesServices.setText("");
    }

    /**
     * Vide les champs de l'onget 'Gestion Chambres'
     */
    private void ViderChampsChambres() {
        txtNumChambre.setText("");
        lblNbCouchages.setText("");
        txtLitsDoubles.setText("");
        txtLitsSimples.setText("");
        txtAddrMac.setText("");
        boxTarifs.removeAllItems();
        ChangerEtatRadBouton(RadioBoutonSdB, 1, true);
        ChangerEtatRadBouton(RadioBoutonWC, 1, true);
    }

    /**
     * Gère le vidage des champs selon le code de l'onglet Codes Onglet : 0 :
     * Hôtel 1 : Chambres 2 : Hôtel + Chambres
     *
     * @param codeOnglet
     */
    private void ViderChamps(int codeOnglet) {
        switch (codeOnglet) {
            case 0:
                ViderChampsHotel();
                break;
            case 1:
                ViderChampsChambres();
                break;
            case 2:
                ViderChampsHotel();
                ViderChampsChambres();
                break;
            default:
                break;
        }
    }

    /// ONGLET
    /// GESTION CHAMBRES
    /**
     * Bouton Ajouter dans l'onglet chambres
     *
     * @param evt
     */
    private void btnAjouterChambreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterChambreActionPerformed
        flagCreationChambre = true;
        OngletChambreAjouter.setVisible(true);
        lblCouchages.setVisible(false);
        lblNbCouchages.setVisible(false);
        ViderChampsChambres();
        RemplirBoxTarifs(6);
    }//GEN-LAST:event_btnAjouterChambreActionPerformed

    private void txtLitsSimplesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLitsSimplesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLitsSimplesActionPerformed

    /**
     * Lève un flagHotel si la combo box dans Gestion Hotel change d'item
     * sélectionné
     *
     * @param evt
     */
    private void comboHotelItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboHotelItemStateChanged

        /*String hotelChoisi = comboHotel.getSelectedItem().toString();

            C_Hotel Hotel = new C_Hotel(hotelChoisi, BDD);

            txtNomHotel.setText(Hotel.getNom());
            txtNumFixe.setText(Hotel.getNumTel());
            txtAdresse.setText(Hotel.getAdresse());
            txtCodePostal.setText(Hotel.getCP());
            txtVille.setText(Hotel.getVille());
            flagHotel = false;
        }*/
 /* Voir l'onglet modification */
    }//GEN-LAST:event_comboHotelItemStateChanged

    private void btnAjouterHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterHotelActionPerformed
        ViderChamps(0);
        flagCreationHotel = true;
        lblStatusHotel.setText("Mode : Création");
        OngletHotelAjouter.setVisible(true);
    }//GEN-LAST:event_btnAjouterHotelActionPerformed

    /**
     * Bouton test qui rempli les valeurs pendant les tests unitaires de
     * l'onglet hotel
     *
     * @param evt
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txtNomHotel.setText("Android");
        txtNumFixe.setText("01.02.99.98.97");
        txtAdresse.setText("Impasse des Lilas");
        txtCodePostal.setText("83640");
        txtVille.setText("Californie");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAnnulerHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnulerHotelActionPerformed
        ViderChamps(1);
        OngletHotelAjouter.setVisible(false);
    }//GEN-LAST:event_btnAnnulerHotelActionPerformed

    private void btnValiderHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValiderHotelActionPerformed
        /* Si le flag de création d'hôtel est levé, on entre dans la boucle de
        création, sinon on est dans la boucle de modification de l'hôtel */
        if (flagCreationHotel) {
            Hotel = new C_Hotel(txtNomHotel.getText(),
                    txtAdresse.getText(),
                    txtVille.getText(),
                    txtCodePostal.getText(),
                    txtNumFixe.getText());
            /* On interroge le retour de la méthode ajouter,
            Si 1 : hôtel ayant les même caractéristiques (doublon)existant dans 
            la BDD
            Si 0 : Pas de doublon, l'hôtel vient d'être ajouté
            Si -1 : Erreur SQL */
            switch (Hotel.Ajouter(BDD)) {
                case 1:
                    JOptionPane.showMessageDialog(rootPane, "Un hôtel présente une "
                            + "ou plusieurs caractéristiques identiques dans la "
                            + "base de donnée",
                            "Hôtel similaire dans la BDD !",
                            JOptionPane.ERROR_MESSAGE);
                    break;
                case -1:
                    JOptionPane.showMessageDialog(rootPane, Hotel.getErrno(),
                            "Erreur SQL", JOptionPane.ERROR_MESSAGE);
                    break;
                case 0:
                    JOptionPane.showMessageDialog(rootPane, "L'hôtel "
                            + "vient d'être ajouté à la base de données !",
                            "Opération réussie",
                            JOptionPane.INFORMATION_MESSAGE);
                    break;
            }
            /* Mise à jour des modifications */
            MettreAJourComboBox(comboHotel, "hotel", BDD);
        } else {
            /* Modification de l'hotel 
            On interroge le résultat de la méthode MettreAJour */
            int res = Hotel.MettreAJour(txtNomHotel.getText(),
                    txtAdresse.getText(),
                    txtCodePostal.getText(),
                    txtVille.getText(),
                    txtNumFixe.getText(), BDD);
            switch (res) {
                case 0:
                    JOptionPane.showMessageDialog(rootPane,
                            "Aucune modification apportée à la base de données",
                            "Opération réussie",
                            JOptionPane.INFORMATION_MESSAGE);
                    break;
                case -1:
                    JOptionPane.showMessageDialog(rootPane, Hotel.getErrno(),
                            "Erreur SQL", JOptionPane.ERROR_MESSAGE);
                    break;
                case 1:
                    JOptionPane.showMessageDialog(rootPane, "L'entrée a été "
                            + "modifiée",
                            "Opération réussie", JOptionPane.INFORMATION_MESSAGE);
                    break;
            }
        }
        MettreAJourComboBox(comboHotelChambre, "hotel", BDD);
    }//GEN-LAST:event_btnValiderHotelActionPerformed

    private void btnModifierHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierHotelActionPerformed
        String hotelChoisi = comboHotel.getSelectedItem().toString();

        Hotel = new C_Hotel(hotelChoisi, BDD);

        txtNomHotel.setText(Hotel.getNom());
        txtNumFixe.setText(Hotel.getNumTel());
        txtAdresse.setText(Hotel.getAdresse());
        txtCodePostal.setText(Hotel.getCP());
        txtVille.setText(Hotel.getVille());
        flagHotel = false;
        flagCreationHotel = false;
        lblStatusHotel.setText("Mode : Modification");

        OngletHotelAjouter.setVisible(true);
    }//GEN-LAST:event_btnModifierHotelActionPerformed

    /**
     * Appelle la méthode de supression d'hôtel
     *
     * @param evt
     */
    private void btnSupprimerHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerHotelActionPerformed
        String hotelChoisi = comboHotel.getSelectedItem().toString();

        Hotel = new C_Hotel(hotelChoisi, BDD);

        /* Message de confirmation pour la suppression d'un hôtel pour éviter
        les suppressions involontaires */
        if (JOptionPane.showConfirmDialog(rootPane, "Etes vous sur de vouloir "
                + "supprimer " + hotelChoisi + " ?", "Attention",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            Hotel.Supprimer(Hotel.getNom(), BDD);
        }
        MettreAJourComboBox(comboHotel, "hotel", BDD);
    }//GEN-LAST:event_btnSupprimerHotelActionPerformed

    /* Quand on clique sur la combo box de l'onglet Hotel */
    private void comboHotelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboHotelMouseClicked
        MettreAJourComboBox(comboHotel, "hotel", BDD);
    }//GEN-LAST:event_comboHotelMouseClicked

    private void comboChambreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboChambreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboChambreActionPerformed

    // INUTILE
    private void comboChambreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboChambreMouseClicked
        /* Cette ligne va dans la version hotel 
        En effet il faut que la combo box s'update dès que l'on clique dessus
         */
        //MettreAJourComboBox(comboChambre, "chambre", BDD);
    }//GEN-LAST:event_comboChambreMouseClicked

    private void comboHotelChambreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboHotelChambreMouseClicked
        //System.out.println("Click !");

    }//GEN-LAST:event_comboHotelChambreMouseClicked

    // INUTILE
    private void comboHotelChambreMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboHotelChambreMouseReleased

    }//GEN-LAST:event_comboHotelChambreMouseReleased

    private void comboHotelChambreItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboHotelChambreItemStateChanged
        /* Si l'état change on recharge la box des chambre, ItemEvent.SELECTED
        permet d'éviter les sorties dupliquées (du à la séléction + désélection
            de l'item */
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            MettreAJourComboBox(comboChambre, "chambre", BDD);
        }
    }//GEN-LAST:event_comboHotelChambreItemStateChanged

    private void btnModifierChambreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierChambreActionPerformed
        /* On rend visible le panel avec toutes les informations */
        flagCreationChambre = false;
        ViderChamps(1);
        OngletChambreAjouter.setVisible(true);
        int numeroChambre = Integer.parseInt(comboChambre.getSelectedItem().toString());

        /* On active les textes avec les couchages */
        if (!lblCouchages.isVisible() && !lblNbCouchages.isVisible()) {
            lblCouchages.setVisible(true);
            lblNbCouchages.setVisible(true);
        }

        /* Chargement des données de la chambre */
        RemplirInfoChambre(numeroChambre, BDD);
    }//GEN-LAST:event_btnModifierChambreActionPerformed

    // GESTION DES RADIOBUTTON DE L'ONGLET CHAMBRE
    private void radSdBOuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radSdBOuiActionPerformed
        ChangerEtatRadBouton(RadioBoutonSdB, 0, true);
    }//GEN-LAST:event_radSdBOuiActionPerformed

    private void radSdBNonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radSdBNonActionPerformed
        ChangerEtatRadBouton(RadioBoutonSdB, 1, true);
    }//GEN-LAST:event_radSdBNonActionPerformed

    private void radWCOuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radWCOuiActionPerformed
        ChangerEtatRadBouton(RadioBoutonWC, 0, true);
    }//GEN-LAST:event_radWCOuiActionPerformed

    private void radWCNonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radWCNonActionPerformed
        ChangerEtatRadBouton(RadioBoutonWC, 1, true);
    }//GEN-LAST:event_radWCNonActionPerformed

    private void comboChambreItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboChambreItemStateChanged
        /* Si l'onglet est visible, alors on charge les infos (évite de 
        gaspiller des ressources) */
        if (OngletChambreAjouter.isVisible()) {
            if (evt.getStateChange() == ItemEvent.SELECTED) {
                int numeroChambre = Integer.parseInt(comboChambre.
                        getSelectedItem().toString());
                /* Chargement des données de la chambre */
                RemplirInfoChambre(numeroChambre, BDD);
            }
        }
    }//GEN-LAST:event_comboChambreItemStateChanged

    /**
     * Bouton 'Valider' pour l'onglet gestion chambres, a deux comportements
     * selon le flag levé : Soit un mode création, soit un mode modification
     *
     * @param evt
     */
    private void btnValiderChambreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValiderChambreActionPerformed
        /* Si le flag est true; on est dans la boucle de création d'hôtel
        Sinon; on est dans la boucle de création d'hôtel */
        if (flagCreationChambre) {
            /* Récupération des positions des radio boutons */
            int SDB = (RadioBoutonSdB[0].isSelected()) ? 1 : 0;
            int WC = (RadioBoutonWC[0].isSelected()) ? 1 : 0;

            Chambre = new C_Chambre();
            int res = Chambre.Ajouter(Integer.parseInt(txtNumChambre.getText()),
                    Integer.parseInt(txtLitsSimples.getText()),
                    Integer.parseInt(txtLitsDoubles.getText()),
                    SDB,
                    WC,
                    boxTarifs.getSelectedItem().toString().charAt(0),
                    txtAddrMac.getText(),
                    comboHotelChambre.getSelectedItem().toString(),
                    BDD);

            switch (res) {
                /* Erreur MySQL */
                case -1:
                    JOptionPane.showMessageDialog(rootPane, Chambre.getErrno(),
                            "Erreur SQL", JOptionPane.ERROR_MESSAGE);
                    break;
                /* Réussite */
                case 0:
                    JOptionPane.showMessageDialog(rootPane, "L'entrée a été "
                            + "ajoutée",
                            "Opération réussie", JOptionPane.INFORMATION_MESSAGE);
                    break;
                /* Doublon existant */
                case 1:
                    JOptionPane.showMessageDialog(rootPane,
                            "Aucune modification apportée à la base de données",
                            "Doublon trouvé",
                            JOptionPane.INFORMATION_MESSAGE);
                    break;
            }

        } else {
            boolean WC = RadioBoutonWC[0].isSelected();
            boolean SDB = RadioBoutonSdB[0].isSelected();
            Chambre = new C_Chambre(Integer.parseInt(txtNumChambre.getText()), BDD);
            int res = Chambre.MettreAJour(Integer.parseInt(txtNumChambre.getText()),
                    Integer.parseInt(txtLitsSimples.getText()),
                    Integer.parseInt(txtLitsDoubles.getText()),
                    SDB,
                    WC,
                    boxTarifs.getSelectedItem().toString().charAt(0),
                    txtAddrMac.getText(),
                    BDD);
            switch (res) {
                /* Réussite */
                default:
                    JOptionPane.showMessageDialog(rootPane, "L'entrée a été "
                            + "modifiée",
                            "Opération réussie", JOptionPane.INFORMATION_MESSAGE);
                    break;
                /* Doublon existant */
                case 0:
                    JOptionPane.showMessageDialog(rootPane,
                            "Aucune modification apportée à la base de données",
                            "Opération réussie",
                            JOptionPane.INFORMATION_MESSAGE);
                    break;
                /* Erreur MySQL */
                case -1:
                    JOptionPane.showMessageDialog(rootPane, Chambre.getErrno(),
                            "Erreur SQL", JOptionPane.ERROR_MESSAGE);
                    break;
            }
        }
        MettreAJourComboBox(comboChambre, "chambre", BDD);
    }//GEN-LAST:event_btnValiderChambreActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        txtLitsSimples.setText("1");
        txtLitsDoubles.setText("1");
        txtNumChambre.setText("140");
        txtAddrMac.setText("10-11-12-13-14-15");
        ChangerEtatRadBouton(RadioBoutonSdB, 0, true);
        ChangerEtatRadBouton(RadioBoutonWC, 0, true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnSupprimerChambreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerChambreActionPerformed
        String hotelChoisi = comboHotelChambre.getSelectedItem().toString();
        int NumeroChambre = Integer.parseInt(
                comboChambre.getSelectedItem().toString());

        Chambre = new C_Chambre(NumeroChambre, BDD);

        if (JOptionPane.showConfirmDialog(rootPane, "Etes vous sur de vouloir "
                + "supprimer la chambre " + NumeroChambre + " de l'hôtel "
                + hotelChoisi +" ?", "Attention",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            Chambre.Supprimer(NumeroChambre, BDD);
        }
        MettreAJourComboBox(comboChambre, "chambre", BDD);
    }//GEN-LAST:event_btnSupprimerChambreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IHM_Principale.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IHM_Principale.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IHM_Principale.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IHM_Principale.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new IHM_Principale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane GestionnaireOnglet;
    private javax.swing.JPanel OngletBilans;
    private javax.swing.JPanel OngletChambreAjouter;
    private javax.swing.JPanel OngletChambres;
    private javax.swing.JPanel OngletCodePerdu;
    private javax.swing.JPanel OngletHotel;
    private javax.swing.JPanel OngletHotelAjouter;
    private javax.swing.JScrollPane OngletModifHotel;
    private javax.swing.JPanel OngletReception;
    private javax.swing.JComboBox<String> boxTarifs;
    private javax.swing.JButton btnAjouterChambre;
    private javax.swing.JButton btnAjouterHotel;
    private javax.swing.JButton btnAjouterServices;
    private javax.swing.JButton btnAnnulerChambre;
    private javax.swing.JButton btnAnnulerHotel;
    private javax.swing.JButton btnCodeChambre;
    private javax.swing.JButton btnGenererBilans;
    private javax.swing.JButton btnModifierChambre;
    private javax.swing.JButton btnModifierHotel;
    private javax.swing.JButton btnOkReservation;
    private javax.swing.JButton btnPaiementRecu;
    private javax.swing.JButton btnSupprimerChambre;
    private javax.swing.JButton btnSupprimerHotel;
    private javax.swing.JButton btnValiderChambre;
    private javax.swing.JButton btnValiderHotel;
    private javax.swing.JComboBox<String> comboChambre;
    private javax.swing.JComboBox<String> comboHotel;
    private javax.swing.JComboBox<String> comboHotelBilans;
    private javax.swing.JComboBox<String> comboHotelChambre;
    private javax.swing.JComboBox<String> comboPeriodeBilan;
    private javax.swing.JComboBox<String> comboServices;
    private javax.swing.JComboBox<String> comboTypeGraphique;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lblAdresse;
    private javax.swing.JLabel lblBilans;
    private javax.swing.JLabel lblCP;
    private javax.swing.JLabel lblChambresReservees;
    private javax.swing.JLabel lblChangerHotel;
    private javax.swing.JLabel lblCouchages;
    private javax.swing.JLabel lblDateArrivee;
    private javax.swing.JLabel lblDateFin;
    private javax.swing.JLabel lblHotelChambres;
    private javax.swing.JLabel lblListeServices;
    private javax.swing.JLabel lblLitsDoubles;
    private javax.swing.JLabel lblLitsSimples;
    private javax.swing.JLabel lblNbCouchages;
    private javax.swing.JLabel lblNbrPersonnes;
    private javax.swing.JLabel lblNomHotel;
    private javax.swing.JLabel lblNomReservation;
    private javax.swing.JLabel lblNumChambre;
    private javax.swing.JLabel lblNumReservation;
    private javax.swing.JLabel lblNumeroFixe;
    private javax.swing.JLabel lblPeriodeBilan;
    private javax.swing.JLabel lblPrenomReservation;
    private javax.swing.JLabel lblPrixRestant;
    private javax.swing.JLabel lblSalleDeBains;
    private javax.swing.JLabel lblStatusHotel;
    private javax.swing.JLabel lblTarif;
    private javax.swing.JLabel lblTypeGraphique;
    private javax.swing.JLabel lblVille;
    private javax.swing.JLabel lblWC;
    private javax.swing.JTextArea listesServices;
    private javax.swing.JPanel panelGraphiqueBilans;
    private javax.swing.JRadioButton radSdBNon;
    private javax.swing.JRadioButton radSdBOui;
    private javax.swing.JRadioButton radWCNon;
    private javax.swing.JRadioButton radWCOui;
    private javax.swing.JSeparator sepReceptionClient;
    private javax.swing.JTextField txtAddrMac;
    private javax.swing.JTextField txtAdresse;
    private javax.swing.JTextField txtCodePostal;
    private javax.swing.JTextField txtDateArrivee;
    private javax.swing.JTextField txtDateFin;
    private javax.swing.JTextField txtLitsDoubles;
    private javax.swing.JTextField txtLitsSimples;
    private javax.swing.JTextField txtNomHotel;
    private javax.swing.JTextField txtNomReservation;
    private javax.swing.JTextField txtNumChambre;
    private javax.swing.JTextField txtNumFixe;
    private javax.swing.JTextField txtNumeroReservation;
    private javax.swing.JTextField txtPrenomReservation;
    private javax.swing.JTextField txtVille;
    // End of variables declaration//GEN-END:variables
}
